first_name = input("Who are you?")
print(f"Hello, {first_name} welcome to Murder Mystery.")
print(f" ")
print(f"**Dramatic Pause**")
print(f" ")
print(f"In this game your mental ability will be pushed to the max.")
first_name = input("Are you ready to proceed?")
if first_name == "yes": print(f"Let's proceed.")
first_name = input("Press Enter to Start >")
print(f"You hear a scream coming from somewhere in the mansion.")
print(f" ")
print(f"AAAAAAAAAAAAAHHHHHHHHH!")
print(f" ")
print(f"You run down to the study to find the maid dead on the floor... It seems as she fell down the stairs.")
print(" ")
first_name = input("Or maybe she was pushed. Press Enter to Proceed >")
first_name = input("Your Job is ot find out... Who killed the maid? What was the murder weapon? >")
print("You walk up to the body to see the Maid lying face down on the marble floor.")
print("You flip her over to see a stab wound in the gut. The wound looks as if the killer twisted the knife. 'This is an act of hatred', you say confidently.")
