print("=========================")
print("   BEST FRIEND MAKER")
print("=========================")

print("Hi. I'm the computer.")
first_name = (f"What's your name?")
fcolor = print(f"Hi, {first_name}! What's your favorite color?")
print(f"No Way! My favorite color is also {fcolor}!")
fmovie = (f"What's your favorite movie?")
print(f" What!/! My favorite movie is also {fmovie}!")
fgame = (f" What is your favorite game?")
